import streamlit as st

# HARDCODED DIRECT VAULT (Perfectly safe because your repository is 100% PRIVATE)
DHAN_CLIENT_ID = "1100533176"
DHAN_ACCESS_TOKEN = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJwX2lwIjoiIiwic19pcCI6IiIsImlzcyI6ImRoYW4iLCJwYXJ0bmVySWQiOiIiLCJleHAiOjE3ODUzOTM1NzYsImlhdCI6MTc4NTMwNzE3NiwidG9rZW5Db25zdW1lclR5cGUiOiJTRUxGIiwid2ViaG9va1VybCI6Imh0dHBzOi8vZm5vLXN3aW5nLWRhc2hib2FyZC1xejdtdmM0emRnY2N3dW5kZjdpa3RjLnN0cmVhbWxpdC5hcHAvIiwiZGhhbkNsaWVudElkIjoiMTEwMDUzMzE3NiJ9.4BaAMsH_ReAYrrZV_RGkYmHQlQYBvoZ5l2dIyRooLYT3WfEA-UYEH9w379ukO7U5jon-iOBzPfcGVBxJ5vfO7A"

# Hardcoded strategy thresholds
MIN_DELIVERY_PCT = 40.0
MAX_IV_RANK_FOR_BUYING = 50.0
DAYS_TO_EXPIRY_THRESHOLD = 7

# Production Endpoint mapping directly to DhanHQ OpenAPI infrastructure
DHAN_BASE_URL = "https://dhan.co"
